fix OpenSSL JRuby loading bug on Travis
The error was:

    NameError: uninitialized constant OpenSSL::OPENSSL_VERSION

It seems to choke when "openssl" is required in a thread.
Not always, though.